language: node_js
node_js:
  - '8.9.0'
before_install:
- pip install --user codecov
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm install -g bower karma grunt-cli"
  - "bower install"
script:
  - npm run travis
branches:
  except:
    - /.*\/.*/
